### ISSUE TITLE
Run the code through the HTML and CSS validators

### ISSUE THREAD

**Issue by jdwilkin4** [jdwilkin4/contrast-ratio-repo#134]
We should run our code through the HTML and CSS validator once the other issues for the version 1 release are complete. 
If there are any issues that come up from the validation reports, we should create tickets for those. 

Here are the validators we will need to use. 
[HTML validator](https://validator.w3.org/)
[CSS validator ](https://jigsaw.w3.org/css-validator/)

**Comment by Okibe00** [comment]
![css validation test](https://user-images.githubusercontent.com/78906040/191960785-d04175f1-1229-4390-a0ea-ec6f7b97e284.png)
![html validation test](https://user-images.githubusercontent.com/78906040/191961115-f6a73202-11ec-426e-b98b-91dcf1e9858d.png)
