### ISSUE TITLE
Move helper functions to helper.js file

### ISSUE THREAD

**Issue by jdwilkin4** [jdwilkin4/contrast-ratio-repo#138]
**This should be worked on after version 1 is deployed**

Our current JavaScript file is a little bloated right now. 
One of the ways we can clean it up is to move all of the helper functions into the `helpers.js` file. 

Examples would include `getLuminance`, `isItNamedColor`, `shortToFullHex`, `hexToRGB`, etc. 

Go through the entire JS file and identify all of the helper functions that can be moved to the  `helpers.js` file. 

If you are new to imports/exports, here is a good article to read.
https://bobbyhadz.com/blog/javascript-import-function-from-another-file

**Comment by AndreyDmitriev39r** [comment]
Should we move them all into `helpers`, or should we split them into several files, depending on function purpose.

For example, we have bunch of fucntions for converting one format to another.

We have functions which are dealing with errors.

That is general idea, I am not sure how it should be done exactly.

**Comment by jdwilkin4** [comment]
Having a file for error handling and one for general helper functions is fine. 
But I don't think we need to have more files than that since it is a small app.

**Comment by ChefDaddyJay** [comment]
I would go ahead and give the namesAndRGBValues constant its own file, maybe just colors.js and keep helpers.js for the functions - the actual "helpers" - seems a little cleaner that way. Just my thoughts.
